apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-test
  labels:
    app: producer-test
spec:
  selector:
    matchLabels:
      app: producer-test
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: producer-test
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: producer-test
        image: apamplin/produce:latest
        imagePullPolicy: Never
